bversion: '3'

services:
    web:
        build: .
        command: python -u app.py
        volumes:
            - .:/app/
        ports:
            - "9750:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
    ourdb:
        image: mongo:latest
